app_name = "paas"
app_title = "PaaS"
app_publisher = "ROKCT INTELLIGENCE (PTY) LTD"
app_description = "PaaS App for Rokct"
app_email = "admin@rokct.ai"
app_license = "AGPL-3.0"

required_apps = ["erpnext"]

# Testing
# -------
before_tests = "paas.tests.utils.before_tests"

# Installation
# ------------
before_install = "paas.install.check_site_role"
after_install = "paas.install.after_install"
before_uninstall = ["paas.builder.utils.prevent_uninstall_if_build_active"]

# Authentication
# --------------
auth_hooks = ["paas.api.auth.auth.validate"]

# Scheduler Events
# ----------------
import frappe  # noqa: E402


def get_safe_scheduler_events():
    """
    Safely get scheduler events by checking if frappe.conf exists.
    This prevents crashes during installation where frappe.conf is not yet available.
    """
    # This function is called at import time, so we must be defensive.
    if not hasattr(frappe, "conf") or not frappe.conf:
        return {}

    app_role = frappe.conf.get("app_role", "tenant")
    events = {}

    if app_role == "tenant":
        # PaaS tasks only run on tenant sites
        events = {
            "hourly": [
                "paas.tasks.process_repeating_orders"
            ],
            "daily": [
                "paas.tasks.remove_expired_stories"
            ]
        }

    return events


scheduler_events = get_safe_scheduler_events()

# Whitelisted Methods
# -------------------
whitelisted_methods = {
    "paas.api.parcel.add_parcel_review": "paas.api.parcel.parcel.add_parcel_review",
    "paas.api.cart.change_status": "paas.api.cart.cart.change_status",
    "paas.api.shop.check_cashback": "paas.api.shop.shop.check_cashback",
    "paas.api.lending.check_financial_eligibility": "paas.api.lending.lending.check_financial_eligibility",
    "paas.api.lending.check_loan_eligibility": "paas.api.lending.lending.check_loan_eligibility",
    "paas.api.lending.check_loan_history_eligibility": "paas.api.lending.lending.check_loan_history_eligibility",
    "paas.api.cart.create_and_cart": "paas.api.cart.cart.create_and_cart",
    "paas.api.cart.create_cart": "paas.api.cart.cart.create_cart",
    "paas.api.lending.create_loan_application": "paas.api.lending.lending.create_loan_application",
    "paas.api.parcel.create_parcel_order": "paas.api.parcel.parcel.create_parcel_order",
    "paas.api.shop.create_shop": "paas.api.shop.shop.create_shop",
    "paas.api.payment.create_transaction": "paas.api.payment.payment.create_transaction",
    "paas.api.user.delete_account": "paas.api.user.user.delete_account",
    "paas.api.payment.delete_card": "paas.api.payment.payment.delete_card",
    "paas.api.cart.delete_cart": "paas.api.cart.cart.delete_cart",
    "paas.api.cart.delete_user": "paas.api.cart.cart.delete_user",
    "paas.api.lending.disburse_loan": "paas.api.lending.lending.disburse_loan",
    "paas.api.lending.fetch_saved_application": "paas.api.lending.lending.fetch_saved_application",
    "paas.api.lending.fetch_saved_applications": "paas.api.lending.lending.fetch_saved_applications",
    "paas.api.user.forgot_password_confirm": "paas.api.user.user.forgot_password_confirm",
    "paas.api.user.forgot_password_confirm": "paas.api.user.user.forgot_password_confirm",
    "paas.api.banner.get_ad": "paas.api.banner.banner.get_ad",
    "paas.api.banner.get_ads": "paas.api.banner.banner.get_ads",
    "paas.api.banner.get_banner": "paas.api.banner.banner.get_banner",
    "paas.api.banner.get_banners": "paas.api.banner.banner.get_banners",
    "paas.api.cart.get_cart_in_group": "paas.api.cart.cart.get_cart_in_group",
    "paas.api.delivery.get_driver_location": "paas.api.delivery.delivery.get_driver_location",
    "paas.api.faq.get_faqs": "paas.api.faq.faq.get_faqs",
    "paas.api.system.get_global_settings": "paas.api.system.system.get_global_settings",
    "paas.api.translation.get_mobile_translations": "paas.api.translation.get_mobile_translations",
    "paas.api.lending.get_my_loan_applications": "paas.api.lending.lending.get_my_loan_applications",
    "paas.api.shop.get_nearby_shops": "paas.api.shop.shop.get_nearby_shops",
    "paas.api.notification.get_notification_count": "paas.api.notification.notification.get_notification_count",
    "paas.api.notification.get_user_notifications": "paas.api.notification.notification.get_user_notifications",
    "paas.api.notification.get_notification_settings": "paas.api.notification.notification.get_notification_settings",
    "paas.api.parcel.calculate_price": "paas.api.parcel.parcel.calculate_price",
    "paas.api.parcel.get_types": "paas.api.parcel.parcel.get_types",
    "paas.api.shop.get_shops": "paas.api.shop.shop.get_shops",
    "paas.api.system.get_policy": "paas.api.system.system.get_policy",
    "paas.api.product.get_product_calculations": "paas.api.product.product.get_product_calculations",
    "paas.api.user.get_referral_details": "paas.api.user.user.get_referral_details",
    "paas.api.payment.get_saved_cards": "paas.api.payment.payment.get_saved_cards",
    "paas.api.branch.get_shop_branch": "paas.api.branch.branch.get_shop_branch",
    "paas.api.shop.get_shop_filter": "paas.api.shop.shop.get_shop_filter",
    "paas.api.shop.get_shops_by_ids": "paas.api.shop.shop.get_shops_by_ids",
    "paas.api.shop.get_shops_recommend": "paas.api.shop.shop.get_shops_recommend",
    "paas.api.story.get_story": "paas.api.story.story.get_story",
    "paas.api.product.get_suggest_price": "paas.api.product.product.get_suggest_price",
    "paas.api.tag.get_tags": "paas.api.tag.tag.get_tags",
    "paas.api.system.get_terms": "paas.api.system.system.get_terms",
    "paas.api.notification.get_notification_settings": "paas.api.notification.notification.get_notification_settings",
    "paas.api.parcel.create_parcel_order": "paas.api.parcel.parcel.create_parcel_order",
    "paas.api.cart.insert_cart": "paas.api.cart.cart.insert_cart",
    "paas.api.cart.insert_cart_with_group": "paas.api.cart.cart.insert_cart_with_group",
    "paas.api.cart.join_order": "paas.api.cart.cart.join_order",
    "paas.api.banner.like_banner": "paas.api.banner.banner.like_banner",
    "paas.api.user.login_with_google": "paas.api.user.user.login_with_google",
    "paas.api.lending.mark_application_as_rejected": "paas.api.lending.lending.mark_application_as_rejected",
    "paas.api.notification.mark_notification_logs_as_read": "paas.api.notification.notification.mark_notification_logs_as_read",
    "paas.api.payment.process_direct_card_payment": "paas.api.payment.payment.process_direct_card_payment",
    "paas.api.payment.process_token_payment": "paas.api.payment.payment.process_token_payment",
    "paas.api.payment.process_wallet_top_up": "paas.api.payment.payment.process_wallet_top_up",
    "paas.api.notification.read_all_notifications": "paas.api.notification.notification.read_all_notifications",
    "paas.api.notification.read_one_notification": "paas.api.notification.notification.read_one_notification",
    "paas.api.cart.remove_product_cart": "paas.api.cart.cart.remove_product_cart",
    "paas.api.payout.request_payout": "paas.api.payout.payout.request_payout",
    "paas.api.lending.save_incomplete_loan_application": "paas.api.lending.lending.save_incomplete_loan_application",
    "paas.api.user.search_user": "paas.api.user.user.search_user",
    "paas.api.user.search_user": "paas.api.user.user.search_user",
    "paas.api.user.send_wallet_balance": "paas.api.user.user.send_wallet_balance",
    "paas.api.user.set_active_address": "paas.api.user.user.set_active_address",
    "paas.api.notification.update_notification_settings": "paas.api.notification.notification.update_notification_settings",
    "paas.api.user.register_user": "paas.api.user.user.register_user",
    "paas.api.user.register_user": "paas.api.user.user.register_user",
    "paas.api.cart.start_group_order": "paas.api.cart.cart.start_group_order",
    "paas.api.payment.tip_process": "paas.api.payment.payment.tip_process",
    "paas.api.payment.tokenize_card": "paas.api.payment.payment.tokenize_card",
    "paas.api.notification.update_notification_settings": "paas.api.notification.notification.update_notification_settings",
    "paas.api.user.update_password": "paas.api.user.user.update_password",
    "paas.api.user.update_profile_image": "paas.api.user.user.update_profile_image",
    "paas.api.upload.upload_multi_image": "paas.api.upload.upload.upload_multi_image",
    "paas.api.whatsapp.flow_endpoint": "paas.api.whatsapp.whatsapp.flow_endpoint",
    "paas.api.whatsapp.hook": "paas.api.whatsapp.whatsapp.hook",
    "paas.api.admin_content.create_admin_banner": "paas.api.admin_content.admin_content.create_admin_banner",
    "paas.api.admin_content.create_admin_faq": "paas.api.admin_content.admin_content.create_admin_faq",
    "paas.api.admin_content.create_admin_faq_category": "paas.api.admin_content.admin_content.create_admin_faq_category",
    "paas.api.admin_content.delete_admin_banner": "paas.api.admin_content.admin_content.delete_admin_banner",
    "paas.api.admin_content.delete_admin_faq": "paas.api.admin_content.admin_content.delete_admin_faq",
    "paas.api.admin_content.delete_admin_faq_category": "paas.api.admin_content.admin_content.delete_admin_faq_category",
    "paas.api.admin_content.get_admin_banners": "paas.api.admin_content.admin_content.get_admin_banners",
    "paas.api.admin_content.get_admin_faq_categories": "paas.api.admin_content.admin_content.get_admin_faq_categories",
    "paas.api.admin_content.get_admin_faqs": "paas.api.admin_content.admin_content.get_admin_faqs",
    "paas.api.admin_content.get_admin_stories": "paas.api.admin_content.admin_content.get_admin_stories",
    "paas.api.admin_content.update_admin_banner": "paas.api.admin_content.admin_content.update_admin_banner",
    "paas.api.admin_content.update_admin_faq": "paas.api.admin_content.admin_content.update_admin_faq",
    "paas.api.admin_content.update_admin_faq_category": "paas.api.admin_content.admin_content.update_admin_faq_category",
    "paas.api.admin_data.create_point": "paas.api.admin_data.admin_data.create_point",
    "paas.api.admin_data.create_referral": "paas.api.admin_data.admin_data.create_referral",
    "paas.api.admin_data.delete_point": "paas.api.admin_data.admin_data.delete_point",
    "paas.api.admin_data.delete_referral": "paas.api.admin_data.admin_data.delete_referral",
    "paas.api.admin_data.get_all_points": "paas.api.admin_data.admin_data.get_all_points",
    "paas.api.admin_data.get_all_product_extra_groups": "paas.api.admin_data.admin_data.get_all_product_extra_groups",
    "paas.api.admin_data.get_all_product_extra_values": "paas.api.admin_data.admin_data.get_all_product_extra_values",
    "paas.api.admin_data.get_all_referrals": "paas.api.admin_data.admin_data.get_all_referrals",
    "paas.api.admin_data.get_all_shop_tags": "paas.api.admin_data.admin_data.get_all_shop_tags",
    "paas.api.admin_data.get_all_tags": "paas.api.admin_data.admin_data.get_all_tags",
    "paas.api.admin_data.get_all_translations": "paas.api.admin_data.admin_data.get_all_translations",
    "paas.api.admin_data.get_all_units": "paas.api.admin_data.admin_data.get_all_units",
    "paas.api.admin_data.update_point": "paas.api.admin_data.admin_data.update_point",
    "paas.api.admin_logistics.create_delivery_vehicle_type": "paas.api.admin_logistics.admin_logistics.create_delivery_vehicle_type",
    "paas.api.admin_logistics.create_parcel_order_setting": "paas.api.admin_logistics.admin_logistics.create_parcel_order_setting",
    "paas.api.admin_logistics.delete_delivery_vehicle_type": "paas.api.admin_logistics.admin_logistics.delete_delivery_vehicle_type",
    "paas.api.admin_logistics.delete_parcel_order_setting": "paas.api.admin_logistics.admin_logistics.delete_parcel_order_setting",
    "paas.api.admin_logistics.get_all_delivery_man_delivery_zones": "paas.api.admin_logistics.admin_logistics.get_all_delivery_man_delivery_zones",
    "paas.api.admin_logistics.get_all_delivery_zones": "paas.api.admin_logistics.admin_logistics.get_all_delivery_zones",
    "paas.api.admin_logistics.get_all_shop_closed_days": "paas.api.admin_logistics.admin_logistics.get_all_shop_closed_days",
    "paas.api.admin_logistics.get_all_shop_working_days": "paas.api.admin_logistics.admin_logistics.get_all_shop_working_days",
    "paas.api.admin_logistics.get_delivery_vehicle_types": "paas.api.admin_logistics.admin_logistics.get_delivery_vehicle_types",
    "paas.api.admin_logistics.get_deliveryman_global_settings": "paas.api.admin_logistics.admin_logistics.get_deliveryman_global_settings",
    "paas.api.admin_logistics.get_parcel_order_settings": "paas.api.admin_logistics.admin_logistics.get_parcel_order_settings",
    "paas.api.admin_logistics.update_delivery_vehicle_type": "paas.api.admin_logistics.admin_logistics.update_delivery_vehicle_type",
    "paas.api.admin_logistics.update_deliveryman_global_settings": "paas.api.admin_logistics.admin_logistics.update_deliveryman_global_settings",
    "paas.api.admin_logistics.update_parcel_order_setting": "paas.api.admin_logistics.admin_logistics.update_parcel_order_setting",
    "paas.api.admin_management.create_shop": "paas.api.admin_management.admin_management.create_shop",
    "paas.api.admin_management.delete_shop": "paas.api.admin_management.admin_management.delete_shop",
    "paas.api.admin_management.get_all_roles": "paas.api.admin_management.admin_management.get_all_roles",
    "paas.api.admin_management.get_all_shops": "paas.api.admin_management.admin_management.get_all_shops",
    "paas.api.admin_management.get_all_users": "paas.api.admin_management.admin_management.get_all_users",
    "paas.api.admin_management.update_shop": "paas.api.admin_management.admin_management.update_shop",
    "paas.api.admin_records.assign_deliveryman_to_parcel": "paas.api.admin_records.admin_records.assign_deliveryman_to_parcel",
    "paas.api.admin_records.create_booking": "paas.api.admin_records.admin_records.create_booking",
    "paas.api.admin_records.delete_admin_parcel_order": "paas.api.admin_records.admin_records.delete_admin_parcel_order",
    "paas.api.admin_records.delete_admin_review": "paas.api.admin_records.admin_records.delete_admin_review",
    "paas.api.admin_records.delete_booking": "paas.api.admin_records.admin_records.delete_booking",
    "paas.api.admin_records.get_all_bookings": "paas.api.admin_records.admin_records.get_all_bookings",
    "paas.api.admin_records.get_all_notifications": "paas.api.admin_records.admin_records.get_all_notifications",
    "paas.api.admin_records.get_all_order_refunds": "paas.api.admin_records.admin_records.get_all_order_refunds",
    "paas.api.admin_records.get_all_order_statuses": "paas.api.admin_records.admin_records.get_all_order_statuses",
    "paas.api.admin_records.get_all_orders": "paas.api.admin_records.admin_records.get_all_orders",
    "paas.api.admin_records.get_all_parcel_orders": "paas.api.admin_records.admin_records.get_all_parcel_orders",
    "paas.api.admin_records.get_all_request_models": "paas.api.admin_records.admin_records.get_all_request_models",
    "paas.api.admin_records.get_all_reviews": "paas.api.admin_records.admin_records.get_all_reviews",
    "paas.api.admin_records.get_all_tickets": "paas.api.admin_records.admin_records.get_all_tickets",
    "paas.api.admin_records.update_admin_order_refund": "paas.api.admin_records.admin_records.update_admin_order_refund",
    "paas.api.admin_records.update_admin_review": "paas.api.admin_records.admin_records.update_admin_review",
    "paas.api.admin_records.update_admin_ticket": "paas.api.admin_records.admin_records.update_admin_ticket",
    "paas.api.admin_records.update_booking": "paas.api.admin_records.admin_records.update_booking",
    "paas.api.admin_reports.get_admin_report": "paas.api.admin_reports.admin_reports.get_admin_report",
    "paas.api.admin_reports.get_admin_statistics": "paas.api.admin_reports.admin_reports.get_admin_statistics",
    "paas.api.admin_reports.get_all_seller_payouts": "paas.api.admin_reports.admin_reports.get_all_seller_payouts",
    "paas.api.admin_reports.get_all_shop_bonuses": "paas.api.admin_reports.admin_reports.get_all_shop_bonuses",
    "paas.api.admin_reports.get_all_transactions": "paas.api.admin_reports.admin_reports.get_all_transactions",
    "paas.api.admin_reports.get_all_wallet_histories": "paas.api.admin_reports.admin_reports.get_all_wallet_histories",
    "paas.api.admin_reports.get_multi_company_sales_report": "paas.api.admin_reports.admin_reports.get_multi_company_sales_report",
    "paas.api.admin_settings.create_email_subscription": "paas.api.admin_settings.admin_settings.create_email_subscription",
    "paas.api.admin_settings.delete_email_subscription": "paas.api.admin_settings.admin_settings.delete_email_subscription",
    "paas.api.admin_settings.get_all_currencies": "paas.api.admin_settings.admin_settings.get_all_currencies",
    "paas.api.admin_settings.get_all_email_templates": "paas.api.admin_settings.admin_settings.get_all_email_templates",
    "paas.api.admin_settings.get_all_languages": "paas.api.admin_settings.admin_settings.get_all_languages",
    "paas.api.admin_settings.get_app_settings": "paas.api.admin_settings.admin_settings.get_app_settings",
    "paas.api.admin_settings.get_email_settings": "paas.api.admin_settings.admin_settings.get_email_settings",
    "paas.api.admin_settings.get_email_subscriptions": "paas.api.admin_settings.admin_settings.get_email_subscriptions",
    "paas.api.admin_settings.get_general_settings": "paas.api.admin_settings.admin_settings.get_general_settings",
    "paas.api.admin_settings.update_app_settings": "paas.api.admin_settings.admin_settings.update_app_settings",
    "paas.api.admin_settings.update_currency": "paas.api.admin_settings.admin_settings.update_currency",
    "paas.api.admin_settings.update_email_settings": "paas.api.admin_settings.admin_settings.update_email_settings",
    "paas.api.admin_settings.update_email_template": "paas.api.admin_settings.admin_settings.update_email_template",
    "paas.api.admin_settings.update_general_settings": "paas.api.admin_settings.admin_settings.update_general_settings",
    "paas.api.admin_settings.update_language": "paas.api.admin_settings.admin_settings.update_language",
    "paas.api.admin_system.clear_system_cache": "paas.api.admin_system.admin_system.clear_system_cache",
    "paas.api.admin_system.create_backup": "paas.api.admin_system.admin_system.create_backup",
    "paas.api.admin_system.get_backups": "paas.api.admin_system.admin_system.get_backups",
    "paas.api.admin_system.get_system_info": "paas.api.admin_system.admin_system.get_system_info",
    "paas.api.ads_package.create_ads_package": "paas.api.ads_package.ads_package.create_ads_package",
    "paas.api.ads_package.delete_ads_package": "paas.api.ads_package.ads_package.delete_ads_package",
    "paas.api.ads_package.get_ads_packages": "paas.api.ads_package.ads_package.get_ads_packages",
    "paas.api.ads_package.update_ads_package": "paas.api.ads_package.ads_package.update_ads_package",
    "paas.api.app_links.get_apple_app_site_association": "paas.api.app_links.get_apple_app_site_association",
    "paas.api.app_links.get_assetlinks": "paas.api.app_links.get_assetlinks",
    "paas.api.banner.get_ad": "paas.api.banner.banner.get_ad",
    "paas.api.banner.get_ads": "paas.api.banner.banner.get_ads",
    "paas.api.banner.like_banner": "paas.api.banner.banner.like_banner",
    "paas.api.blog.create_admin_blog": "paas.api.blog.blog.create_admin_blog",
    "paas.api.blog.create_blog": "paas.api.blog.blog.create_blog",
    "paas.api.blog.delete_admin_blog": "paas.api.blog.blog.delete_admin_blog",
    "paas.api.blog.delete_blog": "paas.api.blog.blog.delete_blog",
    "paas.api.blog.get_admin_blogs": "paas.api.blog.blog.get_admin_blogs",
    "paas.api.blog.get_blog": "paas.api.blog.blog.get_blog",
    "paas.api.blog.get_blog_details": "paas.api.blog.blog.get_blog_details",
    "paas.api.blog.get_blogs": "paas.api.blog.blog.get_blogs",
    "paas.api.blog.update_admin_blog": "paas.api.blog.blog.update_admin_blog",
    "paas.api.blog.update_blog": "paas.api.blog.blog.update_blog",
    "paas.api.booking.cancel_my_booking": "paas.api.booking.booking.cancel_my_booking",
    "paas.api.booking.create_booking": "paas.api.booking.booking.create_booking",
    "paas.api.booking.create_booking_slot": "paas.api.booking.booking.create_booking_slot",
    "paas.api.booking.create_reservation": "paas.api.booking.booking.create_reservation",
    "paas.api.booking.create_shop_section": "paas.api.booking.booking.create_shop_section",
    "paas.api.booking.create_table": "paas.api.booking.booking.create_table",
    "paas.api.booking.create_user_booking": "paas.api.booking.booking.create_user_booking",
    "paas.api.booking.delete_booking": "paas.api.booking.booking.delete_booking",
    "paas.api.booking.delete_booking_slot": "paas.api.booking.booking.delete_booking_slot",
    "paas.api.booking.delete_shop_section": "paas.api.booking.booking.delete_shop_section",
    "paas.api.booking.delete_table": "paas.api.booking.booking.delete_table",
    "paas.api.booking.get_booking": "paas.api.booking.booking.get_booking",
    "paas.api.booking.get_booking_slots": "paas.api.booking.booking.get_booking_slots",
    "paas.api.booking.get_my_bookings": "paas.api.booking.booking.get_my_bookings",
    "paas.api.booking.get_my_reservations": "paas.api.booking.booking.get_my_reservations",
    "paas.api.booking.get_shop_bookings": "paas.api.booking.booking.get_shop_bookings",
    "paas.api.booking.get_shop_reservations": "paas.api.booking.booking.get_shop_reservations",
    "paas.api.booking.get_shop_section": "paas.api.booking.booking.get_shop_section",
    "paas.api.booking.get_shop_sections_for_booking": "paas.api.booking.booking.get_shop_sections_for_booking",
    "paas.api.booking.get_shop_user_bookings": "paas.api.booking.booking.get_shop_user_bookings",
    "paas.api.booking.get_table": "paas.api.booking.booking.get_table",
    "paas.api.booking.get_tables_for_section": "paas.api.booking.booking.get_tables_for_section",
    "paas.api.booking.get_user_bookings": "paas.api.booking.booking.get_user_bookings",
    "paas.api.booking.manage_shop_booking_closed_dates": "paas.api.booking.booking.manage_shop_booking_closed_dates",
    "paas.api.booking.manage_shop_booking_working_days": "paas.api.booking.booking.manage_shop_booking_working_days",
    "paas.api.booking.update_booking": "paas.api.booking.booking.update_booking",
    "paas.api.booking.update_booking_slot": "paas.api.booking.booking.update_booking_slot",
    "paas.api.booking.update_reservation_status": "paas.api.booking.booking.update_reservation_status",
    "paas.api.booking.update_shop_section": "paas.api.booking.booking.update_shop_section",
    "paas.api.booking.update_shop_user_booking_status": "paas.api.booking.booking.update_shop_user_booking_status",
    "paas.api.booking.update_table": "paas.api.booking.booking.update_table",
    "paas.api.booking.update_user_booking_status": "paas.api.booking.booking.update_user_booking_status",
    "paas.api.branch.create_branch": "paas.api.branch.branch.create_branch",
    "paas.api.branch.delete_branch": "paas.api.branch.branch.delete_branch",
    "paas.api.branch.get_branch": "paas.api.branch.branch.get_branch",
    "paas.api.branch.get_branches": "paas.api.branch.branch.get_branches",
    "paas.api.branch.update_branch": "paas.api.branch.branch.update_branch",
    "paas.api.brand.create_brand": "paas.api.brand.brand.create_brand",
    "paas.api.brand.delete_brand": "paas.api.brand.brand.delete_brand",
    "paas.api.brand.get_brand_by_uuid": "paas.api.brand.brand.get_brand_by_uuid",
    "paas.api.brand.get_brands": "paas.api.brand.brand.get_brands",
    "paas.api.brand.update_brand": "paas.api.brand.brand.update_brand",
    "paas.api.career.get_admin_careers": "paas.api.career.career.get_admin_careers",
    "paas.api.career.get_career": "paas.api.career.career.get_career",
    "paas.api.career.get_careers": "paas.api.career.career.get_careers",
    "paas.api.cart.add_to_cart": "paas.api.cart.cart.add_to_cart",
    "paas.api.cart.get_cart": "paas.api.cart.cart.get_cart",
    "paas.api.cart.remove_from_cart": "paas.api.cart.cart.remove_from_cart",
    "paas.api.cart.remove_product_cart": "paas.api.cart.cart.remove_product_cart",
    "paas.api.category.create_category": "paas.api.category.category.create_category",
    "paas.api.category.delete_category": "paas.api.category.category.delete_category",
    "paas.api.category.get_categories": "paas.api.category.category.get_categories",
    "paas.api.category.get_category_by_uuid": "paas.api.category.category.get_category_by_uuid",
    "paas.api.category.get_category_types": "paas.api.category.category.get_category_types",
    "paas.api.category.get_children_categories": "paas.api.category.category.get_children_categories",
    "paas.api.category.search_categories": "paas.api.category.category.search_categories",
    "paas.api.category.update_category": "paas.api.category.category.update_category",
    "paas.api.cook.get_cook_order_report": "paas.api.cook.cook.get_cook_order_report",
    "paas.api.cook.get_cook_orders": "paas.api.cook.cook.get_cook_orders",
    "paas.api.coupon.check_coupon": "paas.api.coupon.coupon.check_coupon",
    "paas.api.delivery.check_delivery_zone": "paas.api.delivery.delivery.check_delivery_zone",
    "paas.api.delivery.get_delivery_point": "paas.api.delivery.delivery.get_delivery_point",
    "paas.api.delivery.get_delivery_points": "paas.api.delivery.delivery.get_delivery_points",
    "paas.api.delivery.get_delivery_zone_by_shop": "paas.api.delivery.delivery.get_delivery_zone_by_shop",
    "paas.api.delivery_man.get_banned_shops": "paas.api.delivery_man.delivery_man.get_banned_shops",
    "paas.api.delivery_man.get_deliveryman_delivery_zones": "paas.api.delivery_man.delivery_man.get_deliveryman_delivery_zones",
    "paas.api.delivery_man.get_deliveryman_order_report": "paas.api.delivery_man.delivery_man.get_deliveryman_order_report",
    "paas.api.delivery_man.get_deliveryman_orders": "paas.api.delivery_man.delivery_man.get_deliveryman_orders",
    "paas.api.delivery_man.get_deliveryman_parcel_orders": "paas.api.delivery_man.delivery_man.get_deliveryman_parcel_orders",
    "paas.api.delivery_man.get_deliveryman_settings": "paas.api.delivery_man.delivery_man.get_deliveryman_settings",
    "paas.api.delivery_man.get_deliveryman_statistics": "paas.api.delivery_man.delivery_man.get_deliveryman_statistics",
    "paas.api.delivery_man.get_payment_to_partners": "paas.api.delivery_man.delivery_man.get_payment_to_partners",
    "paas.api.delivery_man.update_deliveryman_settings": "paas.api.delivery_man.delivery_man.update_deliveryman_settings",
    "paas.api.delivery_zone.check_delivery_availability": "paas.api.delivery_zone.delivery_zone.check_delivery_availability",
    "paas.api.delivery_zone.create_delivery_zone": "paas.api.delivery_zone.delivery_zone.create_delivery_zone",
    "paas.api.delivery_zone.delete_delivery_zone": "paas.api.delivery_zone.delivery_zone.delete_delivery_zone",
    "paas.api.delivery_zone.get_shop_delivery_zones": "paas.api.delivery_zone.delivery_zone.get_shop_delivery_zones",
    "paas.api.delivery_zone.update_delivery_zone": "paas.api.delivery_zone.delivery_zone.update_delivery_zone",
    "paas.api.faq.create_faq": "paas.api.faq.faq.create_faq",
    "paas.api.faq.delete_faq": "paas.api.faq.faq.delete_faq",
    "paas.api.faq.get_faqs": "paas.api.faq.faq.get_faqs",
    "paas.api.faq.update_faq": "paas.api.faq.faq.update_faq",
    "paas.api.language.get_default_language": "paas.api.language.language.get_default_language",
    "paas.api.language.get_languages": "paas.api.language.language.get_languages",
    "paas.api.language.get_translations": "paas.api.language.language.get_translations",
    "paas.api.notification.get_default_sms_payload": "paas.api.notification.notification.get_default_sms_payload",
    "paas.api.notification.get_notification_settings": "paas.api.notification.notification.get_notification_settings",
    "paas.api.notification.send_push_notification": "paas.api.notification.notification.send_push_notification",
    "paas.api.notification.update_notification_settings": "paas.api.notification.notification.update_notification_settings",
    "paas.api.order.add_order_review": "paas.api.order.order.add_order_review",
    "paas.api.order.cancel_order": "paas.api.order.order.cancel_order",
    "paas.api.order.create_order": "paas.api.order.order.create_order",
    "paas.api.order.get_calculate": "paas.api.order.order.get_calculate",
    "paas.api.order.get_order_details": "paas.api.order.order.get_order_details",
    "paas.api.order.get_order_statuses": "paas.api.order.order.get_order_statuses",
    "paas.api.order.list_orders": "paas.api.order.order.list_orders",
    "paas.api.order.update_order_status": "paas.api.order.order.update_order_status",
    "paas.api.page.get_admin_pages": "paas.api.page.page.get_admin_pages",
    "paas.api.page.get_admin_web_page": "paas.api.page.page.get_admin_web_page",
    "paas.api.page.get_page": "paas.api.page.page.get_page",
    "paas.api.page.update_admin_web_page": "paas.api.page.page.update_admin_web_page",
    "paas.api.parcel.calculate_price": "paas.api.parcel.parcel.calculate_price",
    "paas.api.parcel.create_parcel_order": "paas.api.parcel.parcel.create_parcel_order",
    "paas.api.parcel.get_parcel_orders": "paas.api.parcel.parcel.get_parcel_orders",
    "paas.api.parcel.get_types": "paas.api.parcel.parcel.get_types",
    "paas.api.parcel.get_user_parcel_order": "paas.api.parcel.parcel.get_user_parcel_order",
    "paas.api.parcel.update_parcel_status": "paas.api.parcel.parcel.update_parcel_status",
    "paas.api.parcel_option.create_parcel_option": "paas.api.parcel_option.parcel_option.create_parcel_option",
    "paas.api.parcel_option.delete_parcel_option": "paas.api.parcel_option.parcel_option.delete_parcel_option",
    "paas.api.parcel_option.get_parcel_options": "paas.api.parcel_option.parcel_option.get_parcel_options",
    "paas.api.parcel_option.update_parcel_option": "paas.api.parcel_option.parcel_option.update_parcel_option",
    "paas.api.parcel_order_setting.create_parcel_order_setting": "paas.api.parcel_order_setting.parcel_order_setting.create_parcel_order_setting",
    "paas.api.parcel_order_setting.delete_parcel_order_setting": "paas.api.parcel_order_setting.parcel_order_setting.delete_parcel_order_setting",
    "paas.api.parcel_order_setting.get_parcel_order_settings": "paas.api.parcel_order_setting.parcel_order_setting.get_parcel_order_settings",
    "paas.api.parcel_order_setting.update_parcel_order_setting": "paas.api.parcel_order_setting.parcel_order_setting.update_parcel_order_setting",
    "paas.api.payment.delete_card": "paas.api.payment.payment.delete_card",
    "paas.api.payment.delete_payfast_card": "paas.api.payment.payment.delete_payfast_card",
    "paas.api.payment.flutterwave_callback": "paas.api.payment.payment.flutterwave_callback",
    "paas.api.payment.get_payfast_settings": "paas.api.payment.payment.get_payfast_settings",
    "paas.api.payment.get_payment_gateway": "paas.api.payment.payment.get_payment_gateway",
    "paas.api.payment.get_payment_gateways": "paas.api.payment.payment.get_payment_gateways",
    "paas.api.payment.get_saved_cards": "paas.api.payment.payment.get_saved_cards",
    "paas.api.payment.get_saved_payfast_cards": "paas.api.payment.payment.get_saved_payfast_cards",
    "paas.api.payment.handle_payfast_callback": "paas.api.payment.payment.handle_payfast_callback",
    "paas.api.payment.handle_paypal_callback": "paas.api.payment.payment.handle_paypal_callback",
    "paas.api.payment.handle_paystack_callback": "paas.api.payment.payment.handle_paystack_callback",
    "paas.api.payment.handle_stripe_webhook": "paas.api.payment.payment.handle_stripe_webhook",
    "paas.api.payment.initiate_flutterwave_payment": "paas.api.payment.payment.initiate_flutterwave_payment",
    "paas.api.payment.initiate_paypal_payment": "paas.api.payment.payment.initiate_paypal_payment",
    "paas.api.payment.initiate_paystack_payment": "paas.api.payment.payment.initiate_paystack_payment",
    "paas.api.payment.log_payment_payload": "paas.api.payment.payment.log_payment_payload",
    "paas.api.payment.process_direct_card_payment": "paas.api.payment.payment.process_direct_card_payment",
    "paas.api.payment.process_payfast_token_payment": "paas.api.payment.payment.process_payfast_token_payment",
    "paas.api.payment.process_token_payment": "paas.api.payment.payment.process_token_payment",
    "paas.api.payment.process_wallet_payment": "paas.api.payment.payment.process_wallet_payment",
    "paas.api.payment.process_wallet_top_up": "paas.api.payment.payment.process_wallet_top_up",
    "paas.api.payment.save_payfast_card": "paas.api.payment.payment.save_payfast_card",
    "paas.api.payment.tokenize_card": "paas.api.payment.payment.tokenize_card",
    "paas.api.product.add_product_review": "paas.api.product.product.add_product_review",
    "paas.api.product.calculate_product_price": "paas.api.product.product.calculate_product_price",
    "paas.api.product.get_discounted_products": "paas.api.product.product.get_discounted_products",
    "paas.api.product.get_product_by_slug": "paas.api.product.product.get_product_by_slug",
    "paas.api.product.get_product_by_uuid": "paas.api.product.product.get_product_by_uuid",
    "paas.api.product.get_product_history": "paas.api.product.product.get_product_history",
    "paas.api.product.get_product_reviews": "paas.api.product.product.get_product_reviews",
    "paas.api.product.get_products": "paas.api.product.product.get_products",
    "paas.api.product.get_products_by_brand": "paas.api.product.product.get_products_by_brand",
    "paas.api.product.get_products_by_category": "paas.api.product.product.get_products_by_category",
    "paas.api.product.get_products_by_ids": "paas.api.product.product.get_products_by_ids",
    "paas.api.product.get_products_by_shop": "paas.api.product.product.get_products_by_shop",
    "paas.api.product.most_sold_products": "paas.api.product.product.most_sold_products",
    "paas.api.product.order_products_calculate": "paas.api.product.product.order_products_calculate",
    "paas.api.product.products_search": "paas.api.product.product.products_search",
    "paas.api.product.read_product_file": "paas.api.product.product.read_product_file",
    "paas.api.product_extra.create_extra_group": "paas.api.product_extra.product_extra.create_extra_group",
    "paas.api.product_extra.create_extra_value": "paas.api.product_extra.product_extra.create_extra_value",
    "paas.api.product_extra.delete_extra_group": "paas.api.product_extra.product_extra.delete_extra_group",
    "paas.api.product_extra.delete_extra_value": "paas.api.product_extra.product_extra.delete_extra_value",
    "paas.api.product_extra.get_extra_groups": "paas.api.product_extra.product_extra.get_extra_groups",
    "paas.api.product_extra.get_extra_values": "paas.api.product_extra.product_extra.get_extra_values",
    "paas.api.product_extra.update_extra_group": "paas.api.product_extra.product_extra.update_extra_group",
    "paas.api.product_extra.update_extra_value": "paas.api.product_extra.product_extra.update_extra_value",
    "paas.api.receipt.get_receipt": "paas.api.receipt.receipt.get_receipt",
    "paas.api.receipt.get_receipts": "paas.api.receipt.receipt.get_receipts",
    "paas.api.remote_config.get_remote_config": "paas.api.remote_config.get_remote_config",
    "paas.api.repeating_order.create_repeating_order": "paas.api.repeating_order.create_repeating_order",
    "paas.api.repeating_order.delete_repeating_order": "paas.api.repeating_order.delete_repeating_order",
    "paas.api.repeating_order.pause_repeating_order": "paas.api.repeating_order.pause_repeating_order",
    "paas.api.repeating_order.resume_repeating_order": "paas.api.repeating_order.resume_repeating_order",
    "paas.api.seller_bonus.get_seller_bonuses": "paas.api.seller_bonus.seller_bonus.get_seller_bonuses",
    "paas.api.seller_customer_management.get_seller_customer_addresses": "paas.api.seller_customer_management.seller_customer_management.get_seller_customer_addresses",
    "paas.api.seller_customer_management.get_seller_request_models": "paas.api.seller_customer_management.seller_customer_management.get_seller_request_models",
    "paas.api.seller_delivery_zone.check_delivery_fee": "paas.api.seller_delivery_zone.seller_delivery_zone.check_delivery_fee",
    "paas.api.seller_delivery_zone.create_seller_delivery_zone": "paas.api.seller_delivery_zone.seller_delivery_zone.create_seller_delivery_zone",
    "paas.api.seller_delivery_zone.delete_seller_delivery_zone": "paas.api.seller_delivery_zone.seller_delivery_zone.delete_seller_delivery_zone",
    "paas.api.seller_delivery_zone.get_seller_delivery_zone": "paas.api.seller_delivery_zone.seller_delivery_zone.get_seller_delivery_zone",
    "paas.api.seller_delivery_zone.get_seller_delivery_zones": "paas.api.seller_delivery_zone.seller_delivery_zone.get_seller_delivery_zones",
    "paas.api.seller_delivery_zone.update_seller_delivery_zone": "paas.api.seller_delivery_zone.seller_delivery_zone.update_seller_delivery_zone",
    "paas.api.seller_invites.get_seller_invites": "paas.api.seller_invites.seller_invites.get_seller_invites",
    "paas.api.seller_logistics.adjust_seller_inventory": "paas.api.seller_logistics.seller_logistics.adjust_seller_inventory",
    "paas.api.seller_logistics.get_seller_delivery_man_delivery_zones": "paas.api.seller_logistics.seller_logistics.get_seller_delivery_man_delivery_zones",
    "paas.api.seller_marketing.create_seller_banner": "paas.api.seller_marketing.seller_marketing.create_seller_banner",
    "paas.api.seller_marketing.create_seller_coupon": "paas.api.seller_marketing.seller_marketing.create_seller_coupon",
    "paas.api.seller_marketing.create_seller_discount": "paas.api.seller_marketing.seller_marketing.create_seller_discount",
    "paas.api.seller_marketing.delete_seller_banner": "paas.api.seller_marketing.seller_marketing.delete_seller_banner",
    "paas.api.seller_marketing.delete_seller_coupon": "paas.api.seller_marketing.seller_marketing.delete_seller_coupon",
    "paas.api.seller_marketing.delete_seller_discount": "paas.api.seller_marketing.seller_marketing.delete_seller_discount",
    "paas.api.seller_marketing.get_ads_packages": "paas.api.seller_marketing.seller_marketing.get_ads_packages",
    "paas.api.seller_marketing.get_seller_banners": "paas.api.seller_marketing.seller_marketing.get_seller_banners",
    "paas.api.seller_marketing.get_seller_coupons": "paas.api.seller_marketing.seller_marketing.get_seller_coupons",
    "paas.api.seller_marketing.get_seller_discounts": "paas.api.seller_marketing.seller_marketing.get_seller_discounts",
    "paas.api.seller_marketing.get_seller_shop_ads_packages": "paas.api.seller_marketing.seller_marketing.get_seller_shop_ads_packages",
    "paas.api.seller_marketing.purchase_shop_ads_package": "paas.api.seller_marketing.seller_marketing.purchase_shop_ads_package",
    "paas.api.seller_marketing.update_seller_banner": "paas.api.seller_marketing.seller_marketing.update_seller_banner",
    "paas.api.seller_marketing.update_seller_coupon": "paas.api.seller_marketing.seller_marketing.update_seller_coupon",
    "paas.api.seller_marketing.update_seller_discount": "paas.api.seller_marketing.seller_marketing.update_seller_discount",
    "paas.api.seller_operations.adjust_seller_inventory": "paas.api.seller_operations.seller_operations.adjust_seller_inventory",
    "paas.api.seller_operations.create_seller_combo": "paas.api.seller_operations.seller_operations.create_seller_combo",
    "paas.api.seller_operations.create_seller_kitchen": "paas.api.seller_operations.seller_operations.create_seller_kitchen",
    "paas.api.seller_operations.create_seller_menu": "paas.api.seller_operations.seller_operations.create_seller_menu",
    "paas.api.seller_operations.create_seller_receipt": "paas.api.seller_operations.seller_operations.create_seller_receipt",
    "paas.api.seller_operations.delete_seller_combo": "paas.api.seller_operations.seller_operations.delete_seller_combo",
    "paas.api.seller_operations.delete_seller_kitchen": "paas.api.seller_operations.seller_operations.delete_seller_kitchen",
    "paas.api.seller_operations.delete_seller_menu": "paas.api.seller_operations.seller_operations.delete_seller_menu",
    "paas.api.seller_operations.delete_seller_receipt": "paas.api.seller_operations.seller_operations.delete_seller_receipt",
    "paas.api.seller_operations.get_seller_combo": "paas.api.seller_operations.seller_operations.get_seller_combo",
    "paas.api.seller_operations.get_seller_combos": "paas.api.seller_operations.seller_operations.get_seller_combos",
    "paas.api.seller_operations.get_seller_inventory_items": "paas.api.seller_operations.seller_operations.get_seller_inventory_items",
    "paas.api.seller_operations.get_seller_kitchens": "paas.api.seller_operations.seller_operations.get_seller_kitchens",
    "paas.api.seller_operations.get_seller_menu": "paas.api.seller_operations.seller_operations.get_seller_menu",
    "paas.api.seller_operations.get_seller_menus": "paas.api.seller_operations.seller_operations.get_seller_menus",
    "paas.api.seller_operations.get_seller_receipts": "paas.api.seller_operations.seller_operations.get_seller_receipts",
    "paas.api.seller_operations.update_seller_combo": "paas.api.seller_operations.seller_operations.update_seller_combo",
    "paas.api.seller_operations.update_seller_kitchen": "paas.api.seller_operations.seller_operations.update_seller_kitchen",
    "paas.api.seller_operations.update_seller_menu": "paas.api.seller_operations.seller_operations.update_seller_menu",
    "paas.api.seller_operations.update_seller_receipt": "paas.api.seller_operations.seller_operations.update_seller_receipt",
    "paas.api.seller_order.get_seller_order_details": "paas.api.seller_order.seller_order.get_seller_order_details",
    "paas.api.seller_order.get_seller_order_refunds": "paas.api.seller_order.seller_order.get_seller_order_refunds",
    "paas.api.seller_order.get_seller_orders": "paas.api.seller_order.seller_order.get_seller_orders",
    "paas.api.seller_order.get_seller_reviews": "paas.api.seller_order.seller_order.get_seller_reviews",
    "paas.api.seller_order.update_seller_order_refund": "paas.api.seller_order.seller_order.update_seller_order_refund",
    "paas.api.seller_order.update_seller_order_status": "paas.api.seller_order.seller_order.update_seller_order_status",
    "paas.api.seller_payout.get_seller_payouts": "paas.api.seller_payout.seller_payout.get_seller_payouts",
    "paas.api.seller_product.create_seller_brand": "paas.api.seller_product.seller_product.create_seller_brand",
    "paas.api.seller_product.create_seller_category": "paas.api.seller_product.seller_product.create_seller_category",
    "paas.api.seller_product.create_seller_extra_group": "paas.api.seller_product.seller_product.create_seller_extra_group",
    "paas.api.seller_product.create_seller_extra_value": "paas.api.seller_product.seller_product.create_seller_extra_value",
    "paas.api.seller_product.create_seller_product": "paas.api.seller_product.seller_product.create_seller_product",
    "paas.api.seller_product.create_seller_tag": "paas.api.seller_product.seller_product.create_seller_tag",
    "paas.api.seller_product.create_seller_unit": "paas.api.seller_product.seller_product.create_seller_unit",
    "paas.api.seller_product.delete_seller_brand": "paas.api.seller_product.seller_product.delete_seller_brand",
    "paas.api.seller_product.delete_seller_category": "paas.api.seller_product.seller_product.delete_seller_category",
    "paas.api.seller_product.delete_seller_extra_group": "paas.api.seller_product.seller_product.delete_seller_extra_group",
    "paas.api.seller_product.delete_seller_extra_value": "paas.api.seller_product.seller_product.delete_seller_extra_value",
    "paas.api.seller_product.delete_seller_product": "paas.api.seller_product.seller_product.delete_seller_product",
    "paas.api.seller_product.delete_seller_tag": "paas.api.seller_product.seller_product.delete_seller_tag",
    "paas.api.seller_product.delete_seller_unit": "paas.api.seller_product.seller_product.delete_seller_unit",
    "paas.api.seller_product.get_seller_brands": "paas.api.seller_product.seller_product.get_seller_brands",
    "paas.api.seller_product.get_seller_categories": "paas.api.seller_product.seller_product.get_seller_categories",
    "paas.api.seller_product.get_seller_extra_groups": "paas.api.seller_product.seller_product.get_seller_extra_groups",
    "paas.api.seller_product.get_seller_extra_values": "paas.api.seller_product.seller_product.get_seller_extra_values",
    "paas.api.seller_product.get_seller_products": "paas.api.seller_product.seller_product.get_seller_products",
    "paas.api.seller_product.get_seller_tags": "paas.api.seller_product.seller_product.get_seller_tags",
    "paas.api.seller_product.get_seller_units": "paas.api.seller_product.seller_product.get_seller_units",
    "paas.api.seller_product.update_seller_brand": "paas.api.seller_product.seller_product.update_seller_brand",
    "paas.api.seller_product.update_seller_category": "paas.api.seller_product.seller_product.update_seller_category",
    "paas.api.seller_product.update_seller_extra_group": "paas.api.seller_product.seller_product.update_seller_extra_group",
    "paas.api.seller_product.update_seller_extra_value": "paas.api.seller_product.seller_product.update_seller_extra_value",
    "paas.api.seller_product.update_seller_product": "paas.api.seller_product.seller_product.update_seller_product",
    "paas.api.seller_product.update_seller_tag": "paas.api.seller_product.seller_product.update_seller_tag",
    "paas.api.seller_product.update_seller_unit": "paas.api.seller_product.seller_product.update_seller_unit",
    "paas.api.seller_reports.get_seller_sales_report": "paas.api.seller_reports.seller_reports.get_seller_sales_report",
    "paas.api.seller_reports.get_seller_statistics": "paas.api.seller_reports.seller_reports.get_seller_statistics",
    "paas.api.seller_shop.get_shop": "paas.api.seller_shop.seller_shop.get_shop",
    "paas.api.seller_shop.set_working_status": "paas.api.seller_shop.seller_shop.set_working_status",
    "paas.api.seller_shop.update_shop": "paas.api.seller_shop.seller_shop.update_shop",
    "paas.api.seller_shop_gallery.create_seller_shop_gallery": "paas.api.seller_shop_gallery.seller_shop_gallery.create_seller_shop_gallery",
    "paas.api.seller_shop_gallery.delete_seller_shop_gallery": "paas.api.seller_shop_gallery.seller_shop_gallery.delete_seller_shop_gallery",
    "paas.api.seller_shop_gallery.get_seller_shop_galleries": "paas.api.seller_shop_gallery.seller_shop_gallery.get_seller_shop_galleries",
    "paas.api.seller_shop_settings.add_seller_shop_closed_day": "paas.api.seller_shop_settings.seller_shop_settings.add_seller_shop_closed_day",
    "paas.api.seller_shop_settings.add_shop_user": "paas.api.seller_shop_settings.seller_shop_settings.add_shop_user",
    "paas.api.seller_shop_settings.create_seller_branch": "paas.api.seller_shop_settings.seller_shop_settings.create_seller_branch",
    "paas.api.seller_shop_settings.delete_seller_branch": "paas.api.seller_shop_settings.seller_shop_settings.delete_seller_branch",
    "paas.api.seller_shop_settings.delete_seller_shop_closed_day": "paas.api.seller_shop_settings.seller_shop_settings.delete_seller_shop_closed_day",
    "paas.api.seller_shop_settings.get_seller_branches": "paas.api.seller_shop_settings.seller_shop_settings.get_seller_branches",
    "paas.api.seller_shop_settings.get_seller_deliveryman_settings": "paas.api.seller_shop_settings.seller_shop_settings.get_seller_deliveryman_settings",
    "paas.api.seller_shop_settings.get_seller_shop_closed_days": "paas.api.seller_shop_settings.seller_shop_settings.get_seller_shop_closed_days",
    "paas.api.seller_shop_settings.get_seller_shop_working_days": "paas.api.seller_shop_settings.seller_shop_settings.get_seller_shop_working_days",
    "paas.api.seller_shop_settings.get_shop_users": "paas.api.seller_shop_settings.seller_shop_settings.get_shop_users",
    "paas.api.seller_shop_settings.remove_shop_user": "paas.api.seller_shop_settings.seller_shop_settings.remove_shop_user",
    "paas.api.seller_shop_settings.update_seller_branch": "paas.api.seller_shop_settings.seller_shop_settings.update_seller_branch",
    "paas.api.seller_shop_settings.update_seller_deliveryman_settings": "paas.api.seller_shop_settings.seller_shop_settings.update_seller_deliveryman_settings",
    "paas.api.seller_shop_settings.update_seller_shop_working_days": "paas.api.seller_shop_settings.seller_shop_settings.update_seller_shop_working_days",
    "paas.api.seller_story.create_seller_story": "paas.api.seller_story.seller_story.create_seller_story",
    "paas.api.seller_story.delete_seller_story": "paas.api.seller_story.seller_story.delete_seller_story",
    "paas.api.seller_story.get_seller_stories": "paas.api.seller_story.seller_story.get_seller_stories",
    "paas.api.seller_story.update_seller_story": "paas.api.seller_story.seller_story.update_seller_story",
    "paas.api.seller_transactions.get_seller_payment_to_partners": "paas.api.seller_transactions.seller_transactions.get_seller_payment_to_partners",
    "paas.api.seller_transactions.get_seller_shop_payments": "paas.api.seller_transactions.seller_transactions.get_seller_shop_payments",
    "paas.api.seller_transactions.get_seller_transactions": "paas.api.seller_transactions.seller_transactions.get_seller_transactions",
    "paas.api.shop.check_driver_zone": "paas.api.shop.shop.check_driver_zone",
    "paas.api.shop.create_shop": "paas.api.shop.shop.create_shop",
    "paas.api.shop.get_nearby_shops": "paas.api.shop.shop.get_nearby_shops",
    "paas.api.shop.get_shop_details": "paas.api.shop.shop.get_shop_details",
    "paas.api.shop.get_shop_types": "paas.api.shop.shop.get_shop_types",
    "paas.api.shop.get_shops": "paas.api.shop.shop.get_shops",
    "paas.api.shop.get_shops_by_ids": "paas.api.shop.shop.get_shops_by_ids",
    "paas.api.shop.search_shops": "paas.api.shop.shop.search_shops",
    "paas.api.stock.create_stock": "paas.api.stock.stock.create_stock",
    "paas.api.stock.delete_stock": "paas.api.stock.stock.delete_stock",
    "paas.api.stock.get_product_stocks": "paas.api.stock.stock.get_product_stocks",
    "paas.api.stock.update_stock": "paas.api.stock.stock.update_stock",
    "paas.api.subscription.assign_subscription_to_shop": "paas.api.subscription.subscription.assign_subscription_to_shop",
    "paas.api.subscription.cancel_shop_subscription": "paas.api.subscription.subscription.cancel_shop_subscription",
    "paas.api.subscription.create_subscription": "paas.api.subscription.subscription.create_subscription",
    "paas.api.subscription.delete_subscription": "paas.api.subscription.subscription.delete_subscription",
    "paas.api.subscription.get_my_shop_subscription": "paas.api.subscription.subscription.get_my_shop_subscription",
    "paas.api.subscription.get_shop_subscriptions": "paas.api.subscription.subscription.get_shop_subscriptions",
    "paas.api.subscription.get_subscription": "paas.api.subscription.subscription.get_subscription",
    "paas.api.subscription.list_subscriptions": "paas.api.subscription.subscription.list_subscriptions",
    "paas.api.subscription.subscribe_my_shop": "paas.api.subscription.subscription.subscribe_my_shop",
    "paas.api.subscription.update_shop_subscription": "paas.api.subscription.subscription.update_shop_subscription",
    "paas.api.subscription.update_subscription": "paas.api.subscription.subscription.update_subscription",
    "paas.api.system.api_status": "paas.api.system.system.api_status",
    "paas.api.system.get_currencies": "paas.api.system.system.get_currencies",
    "paas.api.system.get_global_settings": "paas.api.system.system.get_global_settings",
    "paas.api.system.get_languages": "paas.api.system.system.get_languages",
    "paas.api.system.get_weather": "paas.api.system.system.get_weather",
    "paas.api.system.trigger_system_update": "paas.api.system.system.trigger_system_update",
    "paas.api.translation.create_translation": "paas.api.translation.create_translation",
    "paas.api.translation.delete_translation": "paas.api.translation.delete_translation",
    "paas.api.translation.drop_all_translations": "paas.api.translation.drop_all_translations",
    "paas.api.translation.export_translations": "paas.api.translation.export_translations",
    "paas.api.translation.get_mobile_translations": "paas.api.translation.get_mobile_translations",
    "paas.api.translation.get_translations_paginate": "paas.api.translation.get_translations_paginate",
    "paas.api.translation.import_translations": "paas.api.translation.import_translations",
    "paas.api.translation.restore_all_translations": "paas.api.translation.restore_all_translations",
    "paas.api.translation.truncate_translations": "paas.api.translation.truncate_translations",
    "paas.api.translation.update_translation": "paas.api.translation.update_translation",
    "paas.api.upload.upload_file": "paas.api.upload.upload.upload_file",
    "paas.api.user.add_user_address": "paas.api.user.user.add_user_address",
    "paas.api.user.check_phone": "paas.api.user.user.check_phone",
    "paas.api.user.create_invite": "paas.api.user.user.create_invite",
    "paas.api.user.create_order_refund": "paas.api.user.user.create_order_refund",
    "paas.api.user.create_request_model": "paas.api.user.user.create_request_model",
    "paas.api.user.create_ticket": "paas.api.user.user.create_ticket",
    "paas.api.user.delete_user_address": "paas.api.user.user.delete_user_address",
    "paas.api.user.export_orders": "paas.api.user.user.export_orders",
    "paas.api.user.forgot_password": "paas.api.user.user.forgot_password",
    "paas.api.user.forgot_password_confirm": "paas.api.user.user.forgot_password_confirm",
    "paas.api.user.get_profile": "paas.api.user.user.get_profile",
    "paas.api.user.get_user_address": "paas.api.user.user.get_user_address",
    "paas.api.user.get_user_addresses": "paas.api.user.user.get_user_addresses",
    "paas.api.user.get_user_invites": "paas.api.user.user.get_user_invites",
    "paas.api.user.get_user_membership": "paas.api.user.user.get_user_membership",
    "paas.api.user.get_user_membership_history": "paas.api.user.user.get_user_membership_history",
    "paas.api.user.get_user_notifications": "paas.api.user.user.get_user_notifications",
    "paas.api.user.get_user_order_refunds": "paas.api.user.user.get_user_order_refunds",
    "paas.api.user.get_user_parcel_order": "paas.api.user.user.get_user_parcel_order",
    "paas.api.user.get_user_parcel_orders": "paas.api.user.user.get_user_parcel_orders",
    "paas.api.user.get_user_profile": "paas.api.user.user.get_user_profile",
    "paas.api.user.get_user_request_models": "paas.api.user.user.get_user_request_models",
    "paas.api.user.get_user_shop": "paas.api.user.user.get_user_shop",
    "paas.api.user.get_user_ticket": "paas.api.user.user.get_user_ticket",
    "paas.api.user.get_user_tickets": "paas.api.user.user.get_user_tickets",
    "paas.api.user.get_user_transactions": "paas.api.user.user.get_user_transactions",
    "paas.api.user.get_user_wallet": "paas.api.user.user.get_user_wallet",
    "paas.api.user.get_wallet_history": "paas.api.user.user.get_wallet_history",
    "paas.api.user.login": "paas.api.user.user.login",
    "paas.api.user.login_with_google": "paas.api.user.user.login_with_google",
    "paas.api.user.logout": "paas.api.user.user.logout",
    "paas.api.user.register_device_token": "paas.api.user.user.register_device_token",
    "paas.api.user.register_user": "paas.api.user.user.register_user",
    "paas.api.user.reply_to_ticket": "paas.api.user.user.reply_to_ticket",
    "paas.api.user.search_user": "paas.api.user.user.search_user",
    "paas.api.user.send_phone_verification_code": "paas.api.user.user.send_phone_verification_code",
    "paas.api.user.update_invite_status": "paas.api.user.user.update_invite_status",
    "paas.api.user.update_password": "paas.api.user.user.update_password",
    "paas.api.user.update_profile": "paas.api.user.user.update_profile",
    "paas.api.user.update_seller_shop": "paas.api.user.user.update_seller_shop",
    "paas.api.user.update_user_address": "paas.api.user.user.update_user_address",
    "paas.api.user.update_user_profile": "paas.api.user.user.update_user_profile",
    "paas.api.user.update_user_shop": "paas.api.user.user.update_user_shop",
    "paas.api.user.verify_phone_code": "paas.api.user.user.verify_phone_code",
    "paas.api.user.verify_email_code": "paas.api.user.user.verify_email_code",
    "paas.api.waiter.get_waiter_order_report": "paas.api.waiter.waiter.get_waiter_order_report",
    "paas.api.waiter.get_waiter_orders": "paas.api.waiter.waiter.get_waiter_orders", }

# Fixtures
# ---------
fixtures = [
    {"dt": "DocType", "filters": [["name", "=", dt_name]]}
    for dt_name in [
        "Kitchen Translation",
        "Subscription",
        "Wallet",
        "Brand",
        "Kitchen",
        "Menu",
        "Parcel Order Item",
        "Parcel Category",
        "Parcel Option",
        "Shop Ads Package",
        "Membership",
        "Shop Booking Closed Date",
        "Wallet History",
        "Shop Cart",
        "Coupon Translation",
        "Point",
        "Order Item",
        "User Shop",
        "Seller Payout",
        "Story",
        "Shop Unit",
        "Coupon",
        "Ads Package",
        "Repeating Order",
        "Shop Booking Working Day",
        "Branch",
        "Shop Gallery",
        "Delivery Vehicle Type",
        "Shop Deliveryman Settings",
        "Menu Item",
        "Loan Contract",
        "Product Extra Value",
        "Shop Closed Day",
        "Shop Cart User",
        "Delivery Point",
        "Shop Subscription",
        "Shop Working Day",
        "Shop Category",
        "FAQ Category",
        "Shop Tag",
        "Booking",
        "User Booking",
        "Category Translation",
        "Seller",
        "DeliveryMan Settings",
        "Shop Section",
        "Ticket",
        "Deliveryman Delivery Zone",
        "Coupon Usage",
        "Flutterwave Settings",
        "Device Token",
        "Parcel Order",
        "Email Subscription",
        "Shop Ban",
        "User Membership",
        "Payout",
        "Payment Payload",
        "Combo",
        "User Address",
        "Parcel Order Setting",
        "Banner",
        "Order",
        "Product Translation",
        "Shop Bonus",
        "Cashback Rule",
        "Combo Item",
        "Permission Settings",
        "Project Settings",
        "Email Settings",
        "Request Model",
        "Table",
        "Category",
        "FAQ",
        "Invitation",
        "Product Extra Group",
        "Tag",
        "Order Refund",
        "Loan Application",
        "Saved Card",
        "Ad",
        "Global Settings",
        "Parcel Review",
        "Loan Eligibility Check",
        "Cart User",
        "Google User",
        "Password Reset",
        "Tip",
        "Referral",
        "Shop",
        "Eligible Plan",
        "Career Category",
        "Career",
        "Delivery Zone",
        "Delivery Zone Coordinate",
        "Order Status",
        "Receipt",
        "Receipt Stock",
        "Receipt Instruction",
        "Receipt Ingredient",
        "Receipt Nutrition",
        "User Cart",
        "Cart Detail",
        "Cart",
        "Review",
        "Driver Location",
        "PaaS Translation",
        "Settings",
        "Referral Campaign",
        "Referral Campaign Translation",
    ]
]

# Website Route Rules
website_route_rules = [{"from_route": "/.well-known/assetlinks.json",
                        "to_route": "paas.api.app_links.get_assetlinks"},
                       {"from_route": "/.well-known/apple-app-site-association",
                        "to_route": "paas.api.app_links.get_apple_app_site_association"},
                       ]

# Document Events
# ---------------
doc_events = {
    "Item": {
        "on_update": "paas.paas.doctype.product.product.auto_vectorize_product",
        "after_insert": "paas.paas.doctype.product.product.auto_vectorize_product",
    }}
