# Copyright (c) 2026 RokctAI
# License: GPL-3.0 (part of the erp/ GPLv3 subtree). Generated by
# port/port_erpnext.py — do not hand-edit; change the script and re-run.
"""Neutral stand-ins for ERPNext features excluded from the erp port
because their DocType names collide with doctype names owned by other
fleet SDK modules (see port_report.json["excluded_fleet_collisions"] and
EXCLUDE_FLEET_DOCTYPES in port/port_erpnext.py). Each stand-in keeps its
callers' contract while the feature itself is excised; restoring a
feature means removing its entry from EXCLUDE_FLEET_DOCTYPES (and its
shim here) and re-running the port.
"""

import frappe


def get_brand_defaults(item, company):
	"""Stand-in for erpnext.setup.doctype.brand.brand.get_brand_defaults.

	The erpnext Brand master is excluded from the port (its doctype name
	collides with the commerce repo's products module), and brand-level
	item defaults are gone with it: report no defaults, so callers fall
	through to the item-group / company default chain exactly as upstream
	does for items without a brand."""
	return frappe._dict()
